//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.30 at 02:00:12 PM IST 
//


package com.amazon.AmazonUI;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.amazon.AmazonUI package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.amazon.AmazonUI
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Resultdata }
     * 
     */
    public Resultdata createResultdata() {
        return new Resultdata();
    }

    /**
     * Create an instance of {@link Resultdata.ProductDetail }
     * 
     */
    public Resultdata.ProductDetail createResultdataProductDetail() {
        return new Resultdata.ProductDetail();
    }

    /**
     * Create an instance of {@link Resultdata.Title }
     * 
     */
    public Resultdata.Title createResultdataTitle() {
        return new Resultdata.Title();
    }

    /**
     * Create an instance of {@link Resultdata.Author }
     * 
     */
    public Resultdata.Author createResultdataAuthor() {
        return new Resultdata.Author();
    }

    /**
     * Create an instance of {@link Resultdata.PublishDate }
     * 
     */
    public Resultdata.PublishDate createResultdataPublishDate() {
        return new Resultdata.PublishDate();
    }

    /**
     * Create an instance of {@link Resultdata.ProductDetail.Format }
     * 
     */
    public Resultdata.ProductDetail.Format createResultdataProductDetailFormat() {
        return new Resultdata.ProductDetail.Format();
    }

    /**
     * Create an instance of {@link Resultdata.ProductDetail.Price }
     * 
     */
    public Resultdata.ProductDetail.Price createResultdataProductDetailPrice() {
        return new Resultdata.ProductDetail.Price();
    }

}
